# A config file for Supabase CLI.
# https://supabase.com/docs/guides/cli/config

project_id = "vdkqrqtrftzhbtquzked"

[api]
enabled = true

[functions.livekit-token]
verify_jwt = true

[functions.kozmik-kaskad-spin]
verify_jwt = true

[functions.zeus-spin]
verify_jwt = true

[functions.iap-receipt-verify]
verify_jwt = true

[functions.notification-push]
verify_jwt = false

[functions.admin-gunluk-ozet]
verify_jwt = false

[functions.misafir-cihaz-oturum]
verify_jwt = false

