import type { CuzdanUiPayload } from './CuzdanUiTipleri';

/** Crash-safe fallback — mevcut Tamuso cüzdan görünümü */
export const DEFAULT_CUZDAN_UI_CONFIG: CuzdanUiPayload = {
  schema_version: 1,
  general: {
    screen_name: 'Cüzdan',
    eyebrow: 'HESABIM',
    subtitle: '',
    description: '',
  },
  brand: {
    name: 'MUTA PAY',
    card_type: 'Dijital cüzdan',
    tagline:
      'Ses odası, gönderi, mesaj ve canlı yayın aktiviteleri ile platform ödüllerinin özeti.',
    tagline_visible: true,
  },
  value_summary: {
    enabled: true,
    show_katalog: true,
    show_platform_share: true,
    show_seller_net: true,
    show_payment_note: true,
    show_language_note: true,
    katalog_label: 'Katalog değeri',
    platform_label: 'Platform hizmet payı',
    seller_net_label: 'Tahmini hesap özeti',
    payment_note:
      'Hesap hareketleri ayın 01–15 ve 15–31 dönemlerinde işlenir.',
    language_note:
      'Gösterilen tutarlar uygulama içi sanal öğe katalog özetidir; gerçek para ödemesi değildir.',
  },
  wallet_icon: {
    source: 'ionicon',
    ionicon: 'wallet-outline',
    url: null,
    size: 22,
    color: '#FFFFFF',
    background: 'rgba(232,64,145,0.22)',
    radius: 14,
    opacity: 1,
    visible: true,
  },
  coin: {
    name: 'Coin',
    short_name: 'Coin',
    source: 'ionicon',
    ionicon: 'ellipse',
    url: null,
    color: '#F0B429',
    gradient_start: '#F0B429',
    gradient_end: '#E84091',
    size: 18,
    placement: 'before',
    show_beside_amount: true,
  },
  theme: {
    preset: 'premium',
    background: '#0B0614',
    surface: '#16121E',
    cardBackground: '#1A1424',
    primary: '#E84091',
    secondary: '#8B5CF6',
    accent: '#F0B429',
    buttonBackground: 'rgba(232,64,145,0.16)',
    buttonText: '#FFFFFF',
    primaryText: '#FFFFFF',
    secondaryText: 'rgba(255,255,255,0.62)',
    border: 'rgba(255,255,255,0.10)',
    positive: '#34D399',
    warning: '#F0B429',
    gradientStart: '#E84091',
    gradientEnd: '#8B5CF6',
    gradientDirection: 'vertical',
    radius: 16,
  },
  sections: [
    { key: 'header', enabled: true, sort_order: 10 },
    { key: 'hero_card', enabled: true, sort_order: 20 },
    { key: 'quick_actions', enabled: true, sort_order: 30 },
    { key: 'summary', enabled: true, sort_order: 40 },
    { key: 'tabs', enabled: true, sort_order: 50 },
    { key: 'coin_info', enabled: true, sort_order: 60 },
    { key: 'ledger', enabled: true, sort_order: 70 },
    { key: 'gifts', enabled: true, sort_order: 80 },
    { key: 'topup', enabled: true, sort_order: 90 },
    { key: 'withdraw', enabled: true, sort_order: 100 },
  ],
  actions: [
    {
      key: 'takas',
      enabled: true,
      title: 'Coin takas',
      subtitle: 'Hesaplar arası transfer',
      icon: 'swap-horizontal',
      icon_type: 'ionicon',
      icon_color: '#F0B429',
      background_color: 'rgba(255,255,255,0.06)',
      text_color: '#FFFFFF',
      sort_order: 10,
      action_type: 'route',
      action_target: '/cuzdan/takas',
      requires_flag: 'wallet_exchange_enabled',
    },
    {
      key: 'kyc',
      enabled: true,
      title: 'Kimlik onayı',
      subtitle: '',
      icon: 'shield-checkmark-outline',
      icon_type: 'ionicon',
      icon_color: '#E84091',
      background_color: 'rgba(255,255,255,0.06)',
      text_color: '#FFFFFF',
      sort_order: 20,
      action_type: 'route',
      action_target: '/kyc',
      requires_flag: null,
    },
    {
      key: 'hareket_belge',
      enabled: true,
      title: 'Hesap özeti',
      subtitle: 'PDF / Excel',
      icon: 'document-text-outline',
      icon_type: 'ionicon',
      icon_color: '#FFFFFF',
      background_color: 'rgba(255,255,255,0.06)',
      text_color: '#FFFFFF',
      sort_order: 30,
      action_type: 'open_statement',
      action_target: null,
      requires_flag: null,
    },
  ],
  texts: [
    {
      key: 'coin_info',
      type: 'info',
      enabled: true,
      sort_order: 10,
      style_variant: 'footnote',
      locales: {
        tr: 'Coinler Tamuso içinde kullanılan sanal öğelerdir; uygulama dışı gerçek para ödemesi değildir.',
        en: 'Coins are virtual items used within Tamuso; they are not a real-money payout outside the app.',
        ar: 'العملات عناصر افتراضية داخل تاموسو وليست مدفوعات نقدية خارج التطبيق.',
      },
    },
    {
      key: 'purchase_locked',
      type: 'warning',
      enabled: true,
      sort_order: 20,
      style_variant: 'warning',
      locales: {
        tr: 'Satın alma geçici olarak kapalı.',
        en: 'Purchases are temporarily unavailable.',
        ar: 'الشراء غير متاح مؤقتاً.',
      },
    },
    {
      key: 'summary_title',
      type: 'heading',
      enabled: true,
      sort_order: 5,
      style_variant: 'section',
      locales: { tr: 'Özet', en: 'Summary', ar: 'ملخص' },
    },
    {
      key: 'hero_note',
      type: 'info',
      enabled: true,
      sort_order: 8,
      style_variant: 'footnote',
      locales: {
        tr: 'Cüzdan bakiyen; içerik, hediye ve platform aktivitelerini yönetmek içindir.',
        en: 'Your wallet balance helps manage content, gifts, and platform activity.',
        ar: 'رصيد محفظتك لإدارة المحتوى والهدايا ونشاط المنصة.',
      },
    },
  ],
  assets: {
    banner_url: null,
    empty_state_url: null,
  },
};
