/**
 * Server tarafindan yonetilen feature flag anahtarlari.
 * Degerler hard-code business rule degil; remote config.
 */
export const OzellikBayragiAnahtarlari = [
  'voice_rooms_enabled',
  'live_enabled',
  'video_enabled',
  'gifts_enabled',
  'pk_enabled',
  'agency_enabled',
  'withdrawals_enabled',
  'wallet_exchange_enabled',
  'wallet_sell_enabled',
  'wallet_withdraw_enabled',
  'city_league_enabled',
  'city_battles_enabled',
  'city_elections_enabled',
  'messages_enabled',
  'events_enabled',
  'missions_enabled',
  'announcements_enabled',
  'auto_promo_banners_enabled',
  'auto_event_banners_enabled',
  'policies_enabled',
  'moderation_enabled',
  'analytics_enabled',
  'certification_hub_enabled',
  'low_end_mode_enabled',
  'graceful_degradation_enabled',
  'stress_tools_enabled',
  'iap_enabled',
  'stripe_enabled',
  'games_enabled',
  'kozmik_kaskad_enabled',
  'zeus_enabled',
  'nox_reels_enabled',
  'voice_room_music_enabled',
  'music_ducking_enabled',
  'music_playlists_enabled',
  'music_favorites_enabled',
  'ai_music_enabled',
  'ai_music_reference_enabled',
  'ai_music_status_share_enabled',
  'ai_music_voice_room_enabled',
  'ai_music_export_enabled',
  'transaction_volume_enabled',
  'transaction_volume_profile_enabled',
  'transaction_volume_tiers_enabled',
  'transaction_volume_leaderboard_enabled',
  'transaction_volume_effects_enabled',
  'people_discovery_enabled',
  'people_personalized_enabled',
  'people_gender_filter_enabled',
  'people_country_filter_enabled',
  'people_online_filter_enabled',
  'people_price_filter_enabled',
  'people_message_enabled',
  'people_voice_call_enabled',
  'people_video_call_enabled',
  'people_paid_calling_enabled',
  'people_show_prices_enabled',
  'people_show_country_flags',
  'people_show_online_indicators',
] as const;

export type OzellikBayragiAnahtari = (typeof OzellikBayragiAnahtarlari)[number];

/** Kritik sistem acil durdurma */
export const KillSwitchAnahtarlari = [
  'kill_coin_purchase',
  'kill_gift_send',
  'kill_withdrawal',
  'kill_agency_coin_transfer',
  'kill_live',
  'kill_pk',
  'kill_moderation',
  'kill_heavy_animations',
  'kill_livekit_reconnect',
  'kill_games',
  'kill_game_coin',
  'kill_ai_music_generation',
  'kill_transaction_volume_display',
  'kill_people_discovery',
  'kill_people_paid_calls',
] as const;

export type KillSwitchAnahtari = (typeof KillSwitchAnahtarlari)[number];
